version: "3"

services:

  php:
    image: php:7.1
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    command: bash

  node:
    image: node:8
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    command: bash

  cp2s3:
    image: quay.io/keboola/aws-cli
    tty: true
    volumes:
      - ./:/code
    working_dir: /code
    command: >-
             s3 cp dist s3://misc-ui-assets/misc-ui
             --recursive
             --exclude "index.html"
             --acl "public-read"
             --cache-control "max-age=600"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
